envRule:
    dev: 
        - 10.1.55.
        - 10.2.56.
    test: 
        - 22.56.11.
        - 23.
    pre: 
        - 192.168.244.
        - 172.30.200.

group:
    group1:
        - ${group2}
        - test.host.com
        - mouse.wiki
        - www.changer.com

    group2:
        - test2.host.com
        - mouse2.wiki
        - www.changer2.com

address:
  test.host.com:
    - 10.1.55.22
    - 23.2.2.2
    - 172.30.200.2
  mouse.wiki:
    - 22.56.11.2
    - 192.168.244.10
  www.changer.com:
    - 192.168.244.3
  test2.host.com:
    - 10.2.56.12
    - 23.99.2.2
  friend.nx.com:
    - 125.141.158.210
    - 183.110.0.112
  mouse2.wiki:
    - 10.1.55.12
    - 172.30.200.200
  www.changer2.com:
    - 10.2.56.80
    - 172.30.200.90